[workspace]
members = ["dfdx-nn-core", "dfdx-nn-derives", "dfdx-nn"]
resolver = "2"

[workspace.dependencies]
dfdx = { git = "https://github.com/coreylowman/dfdx.git", features = ["nightly", "safetensors"] }
safetensors = { version = "0.3", default-features = false }
